### ISSUE TITLE
What's the environment?

### ISSUE THREAD

**Issue by kingaza** [khammernik/sigmanet#2]
Hello Kerstin,

It is really a great job~
I want to reproduce your work, but I am wandering if one or two 1080Ti can handle with the huge GPU memory consumption, as mentioned in the paper.

So could you show me your environment? Thanks a lot.

Best Regards,
He Jin Qiang

**Comment by khammernik** [comment]
Hi,

It's possible to fit everything on a single 1080Ti. We use data pre-processing as described in the readme and patch-based training.

OS: Ubuntu 16.04 LTS
32GB RAM
Nvidia GPU: GeForce GTX 1080 Ti

hth,
Kerstin

**Comment by kingaza** [comment]
@khammernik thx a lot.
